### ISSUE TITLE
"Error: No filename found. This is likely a bug in expo-router."

### ISSUE THREAD

**Issue by dawickizer** [expo/router#416]
### Summary

When running Jest unit tests with `react-test-renderer` for a React Native application that uses expo and expo-router, I am receiving the error message "No filename found. This is likely a bug in expo-router." I am unsure what is causing this error and would appreciate any assistance in resolving it. The problematic piece is the `<Stack />` component from `expo-router`.

### Minimal reproducible example

`NavigationBarComponent.tsx`:
```
import { Stack } from 'expo-router';

export default function NavigationBarComponent() {
  return <Stack props={{props}} />;
}
```

`NavigationBarComponent.test.tsx`:
```
import React from 'react';
import renderer from 'react-test-renderer';
import NavigationBarComponent from './NavigationBarComponent';

describe('<NavigationBarComponent />', () => {
  it('exists', () => {
    const tree : any = renderer.create(<NavigationBarComponent/>).toJSON();
    expect(tree).not.toBeNull();
  });
});
```

Error:
```
<NavigationBarComponent /> › exists

    No filename found. This is likely a bug in expo-router.

       5 | describe('<NavigationBarComponent />', () => {
       6 |   it('exists', () => {
    >  7 |     const tree : any = renderer.create(<NavigationBarComponent/>).toJSON();
         |                                 ^
       8 |     expect(tree).not.toBeNull();
       9 |   });
      10 | });

      at useContextKey (node_modules/expo-router/src/Route.tsx:40:11)
      at node_modules/expo-router/src/layouts/withLayoutContext.tsx:88:39
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6351:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9150:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11361:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15811:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15745:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15717:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15422:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushSyncCallbacksOnlyInLegacyMode (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2576:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14910:7)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17770:5)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18510:3)
      at Object.create (src/components/navigation-bar/NavigationBarComponent.test.tsx:7:33)
```

**Comment by Ricky428** [comment]
I'm facing the same issue and I'm not using any testing library

**Comment by 0tabek16** [comment]
@Ricky428 have you tried to use `renderRouter()` test util?

**Comment by Ricky428** [comment]
> @Ricky428 have you tried to use `renderRouter()` test util?

No i don't know about it mate but I figured out that I was missing index.tsx file according to docs _layout.tsx is compulsory and there is no mention of index.tsx file so I didn't care about the it.

**Comment by andrei-m-code** [comment]
I fixed the issue with `useNavigation()` by importing it from `react-navigation/native` instead of `expo-router`.

✅ Works:

    import {useNavigation} from "@react-navigation/native"

❌ Doesn't work:

    import {useNavigation} from "expo-router"
