### ISSUE TITLE
TypeError: isAssetFile is not a function

### ISSUE THREAD

**Issue by nephix** [expo/router#557]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

I created an expo router app via template and upgraded to expo sdk 48

When running the app, I get:

```
TypeError: isAssetFile is not a function
    at resolveFile (/Users/nephix/Projects/expo-router-repro/node_modules/metro-resolver/src/resolve.js:272:7)
    at resolveFileOrDir (/Users/nephix/Projects/expo-router-repro/node_modules/metro-resolver/src/resolve.js:198:22)
    at resolveModulePath (/Users/nephix/Projects/expo-router-repro/node_modules/metro-resolver/src/resolve.js:130:18)
    at resolve (/Users/nephix/Projects/expo-router-repro/node_modules/metro-resolver/src/resolve.js:37:12)
    at /Users/nephix/Projects/expo-router-repro/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:92:28
    at resolveRequest (/Users/nephix/Projects/expo-router-repro/node_modules/@expo/cli/build/src/start/server/metro/withMetroResolvers.js:26:44)
    at Object.resolve (/Users/nephix/Projects/expo-router-repro/apps/expo-app/node_modules/metro/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (/Users/nephix/Projects/expo-router-repro/apps/expo-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/nephix/Projects/expo-router-repro/apps/expo-app/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at /Users/nephix/Projects/expo-router-repro/apps/expo-app/node_modules/metro/src/lib/transformHelpers.js:169:21
› Stopped server
```

I would expect it to start without problems

### Minimal reproducible example

```sh
git clone https://github.com/nephix/expo-router-repro
cd expo-router-repro
npm install
cd apps/expo-app
npx expo start --ios
```

**Comment by holmesjr** [comment]
This appears to be related to later version of metro. If you lock to older versions as described in the overrides section on https://expo.github.io/router/docs/, the issue goes away. I saw different resolved metro-runtime versions between two expo web apps: 1.x on one I updated and 2.x on one I just created today. The one I created today has this issue.

**Comment by nephix** [comment]
I'm getting the same error after updating the version numbers of the `overrides` in the example repo I linked in the OP @holmesjr

**Comment by MundoKaizen** [comment]
I had this error for a few hours. Solved it with the above suggestion, plus the good old-fashioned dependency wipe. Removed node_modules and package-lock.json. Then re-installed with the commaned "npx expo install". Can't do normal "npm install".

**Comment by EvanBacon** [comment]
Please upgrade to Expo SDK 49, Expo Router v2, and remove all metro overrides.

**Comment by azizsaad** [comment]
Appreciate this issue is closed, but I'm getting this error after upgrading to SDK 49

- Added metro as the web bundler (despite not using RN web)
- doctor runs fine and dependencies fixes are all fine
- installed metro as a dev-dependency

Not using Expo Router in my project. Appreciate any help on this 🙌

**Comment by azizsaad** [comment]
> Appreciate this issue is closed, but I'm getting this error after upgrading to SDK 49
> 
> * Added metro as the web bundler (despite not using RN web)
> * doctor runs fine and dependency fixes are all fine
> * installed metro as a dev-dependency ("^0.79.0")
> * don't have any overrides
> 
> Not using Expo Router in my project. Appreciate any help on this 🙌

Nevermind - I solved this by simply installing the latest version of `metro resolver`

**Comment by byteab** [comment]
This error is still happening even with expo SDK 51 and expo-router `3.5.16`.
even tried with a fresh project  using `npx create-expo-app@latest`

**Comment by sainjay** [comment]
@EvanBacon facing this in GItHub actions. Any clue to what could be the problem?

Expo - 51.0.26
Expo Router - 3.5.15

`TypeError: isAssetFile is not a function
    at resolveFile (/home/runner/work/node_modules/metro-resolver/src/resolve.js:344:7)
    at resolveFileOrDir (/home/runner/work/node_modules/metro-resolver/src/resolve.js:258:22)
    at resolveModulePath (/home/runner/work/node_modules/metro-resolver/src/resolve.js:180:18)
    at resolver (/home/runner/work/node_modules/metro-resolver/src/resolve.js:63:12)
    at doResolve (/home/runner/work/node_modules/@expo/cli/src/start/server/metro/withMetroMultiPlatform.ts:242:14)
    at resolver (/home/runner/work/node_modules/@expo/cli/src/start/server/metro/withMetroMultiPlatform.ts:382:22)
    at firstResolver (/home/runner/work/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:76:29)
    at firstResolver (/home/runner/work/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:108:16)
    at resolveRequest (/home/runner/work/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:137:16)
    at Object.resolve (/home/runner/work/node_modules/metro/node_modules/metro-resolver/src/resolve.js:32:12)`

**Comment by sainjay** [comment]
On Expo 51, able to build the app with experimental flag `EXPO_USE_FAST_RESOLVER=1` but the app was crashing in real device.

 Tried installing the latest version of `metro-resolver`, fixed the issue with the build but still experiencing crash.

**Comment by samducker** [comment]
@EvanBacon the issue is also still present on Expo SDK 52

    "expo-router": "4.0.17",     "react-native": "0.76.7",
