### ISSUE TITLE
PluginError: Package "expo-router" does not contain a valid config plugin.

### ISSUE THREAD

**Issue by AlexGrafe** [expo/router#676]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Hi everyone,
the `<Head>` component requires the `expo-router` config plugin in `app.json`/`app.config.js` but that's throwing below error for me. FYI I'm using `app.config.ts` (Typescript) and everything else works smoothly.

Docs: https://expo.github.io/router/docs/features/head/#beta-notice

```
PluginError: Package "expo-router" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'export'
/Users/alex/Development/xanderia/src/client/node_modules/expo-router/src/index.tsx:1
export { Stack } from "./layouts/Stack";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at requirePluginFile (/Users/alex/Development/xanderia/src/client/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:214:12)
    at resolveConfigPluginFunctionWithInfo (/Users/alex/Development/xanderia/src/client/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:155:14)
```

### Minimal reproducible example

1. npx create-expo-app@latest --example with-router
2. add `plugins` section as per docs to `app.json`/`app.config.js`
3. add `<Head>` on a page

**Comment by EvanBacon** [comment]
Try with `expo-router@next` i.e. v2
